//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card details.
        /// </summary>
        internal static string CardPage_CardDetailsLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardDetailsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter manually.
        /// </summary>
        internal static string CardPage_CardEntryModeDropDownList_Manual
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardEntryModeDropDownList_Manual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swipe card.
        /// </summary>
        internal static string CardPage_CardEntryModeDropDownList_Swipe
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardEntryModeDropDownList_Swipe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Voice authorization.
        /// </summary>
        internal static string CardPage_CardEntryModeDropDownList_Voice
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardEntryModeDropDownList_Voice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card input.
        /// </summary>
        internal static string CardPage_CardEntryModeLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardEntryModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card holder name.
        /// </summary>
        internal static string CardPage_CardHolderNameLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardHolderNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        internal static string CardPage_CardNumberLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardNumberLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to American Express.
        /// </summary>
        internal static string CardPage_CardTypeDropDownList_AmericanExpress
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardTypeDropDownList_AmericanExpress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string CardPage_CardTypeDropDownList_Discover
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardTypeDropDownList_Discover", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Master Card.
        /// </summary>
        internal static string CardPage_CardTypeDropDownList_MasterCard
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardTypeDropDownList_MasterCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        internal static string CardPage_CardTypeDropDownList_PleaseSelect
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardTypeDropDownList_PleaseSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VISA.
        /// </summary>
        internal static string CardPage_CardTypeDropDownList_Visa
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardTypeDropDownList_Visa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card type.
        /// </summary>
        internal static string CardPage_CardTypeLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_CardTypeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CardPage_CityLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_CityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while communicating to server. Please contact your administrator..
        /// </summary>
        internal static string CardPage_CommunicationError
        {
            get
            {
                return ResourceManager.GetString("CardPage_CommunicationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        internal static string CardPage_CountryRegionDropDownList_CA
        {
            get
            {
                return ResourceManager.GetString("CardPage_CountryRegionDropDownList_CA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        internal static string CardPage_CountryRegionDropDownList_PleaseSelect
        {
            get
            {
                return ResourceManager.GetString("CardPage_CountryRegionDropDownList_PleaseSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to United States of America.
        /// </summary>
        internal static string CardPage_CountryRegionDropDownList_US
        {
            get
            {
                return ResourceManager.GetString("CardPage_CountryRegionDropDownList_US", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country/region.
        /// </summary>
        internal static string CardPage_CountryRegionLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_CountryRegionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One or more address fields are missing..
        /// </summary>
        internal static string CardPage_Error_InvalidAddress
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_InvalidAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment amount is invalid..
        /// </summary>
        internal static string CardPage_Error_InvalidAmount
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_InvalidAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The card is invalid..
        /// </summary>
        internal static string CardPage_Error_InvalidCard
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_InvalidCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card number is invalid. .
        /// </summary>
        internal static string CardPage_Error_InvalidCardNumber
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_InvalidCardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card type is invalid..
        /// </summary>
        internal static string CardPage_Error_InvalidCardType
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_InvalidCardType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid request ID..
        /// </summary>
        internal static string CardPage_Error_InvalidRequestId
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_InvalidRequestId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security code is invalid. .
        /// </summary>
        internal static string CardPage_Error_InvalidSecurityCode
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_InvalidSecurityCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card holder first name is missing..
        /// </summary>
        internal static string CardPage_Error_MissingCardHolderFirstName
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_MissingCardHolderFirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card holder last name is missing..
        /// </summary>
        internal static string CardPage_Error_MissingCardHolderLastName
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_MissingCardHolderLastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card number is missing. .
        /// </summary>
        internal static string CardPage_Error_MissingCardNumber
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_MissingCardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card type is missing. .
        /// </summary>
        internal static string CardPage_Error_MissingCardType
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_MissingCardType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expiration month is missing. .
        /// </summary>
        internal static string CardPage_Error_MissingExpirationMonth
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_MissingExpirationMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expiration year is missing. .
        /// </summary>
        internal static string CardPage_Error_MissingExpirationYear
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_MissingExpirationYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request ID is missing..
        /// </summary>
        internal static string CardPage_Error_MissingRequestId
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_MissingRequestId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request has timed out..
        /// </summary>
        internal static string CardPage_Error_RequestTimedOut
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_RequestTimedOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request is already used..
        /// </summary>
        internal static string CardPage_Error_UsedRequest
        {
            get
            {
                return ResourceManager.GetString("CardPage_Error_UsedRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_April
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_April", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_August
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_August", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_December
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_December", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_February
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_February", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_January
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_January", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_July
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_July", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_June
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_June", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_March
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_March", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_May
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_May", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_November
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_November", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_October
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_October", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_PleaseSelect
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_PleaseSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string CardPage_ExpirationMonthDropDownList_September
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthDropDownList_September", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expiration month.
        /// </summary>
        internal static string CardPage_ExpirationMonthLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationMonthLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        internal static string CardPage_ExpirationYearDropDownList_PleaseSelect
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationYearDropDownList_PleaseSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expiration year.
        /// </summary>
        internal static string CardPage_ExpirationYearLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_ExpirationYearLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card track data is invalid..
        /// </summary>
        internal static string CardPage_InvalidCardTrackData
        {
            get
            {
                return ResourceManager.GetString("CardPage_InvalidCardTrackData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ZIP code.
        /// </summary>
        internal static string CardPage_PostalCodeLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_PostalCodeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Same as shipping address.
        /// </summary>
        internal static string CardPage_SameAsShippingAddressCheckbox
        {
            get
            {
                return ResourceManager.GetString("CardPage_SameAsShippingAddressCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        internal static string CardPage_SecurityCodeLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_SecurityCodeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing address.
        /// </summary>
        internal static string CardPage_ShippingAddressLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_ShippingAddressLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State/province.
        /// </summary>
        internal static string CardPage_StateProvinceLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_StateProvinceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string CardPage_StreetLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_StreetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Voice authorization code.
        /// </summary>
        internal static string CardPage_VoiceAuthorizationCodeLabel
        {
            get
            {
                return ResourceManager.GetString("CardPage_VoiceAuthorizationCodeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact the system administrator..
        /// </summary>
        internal static string GenericErrorPage_ErrorLabel
        {
            get
            {
                return ResourceManager.GetString("GenericErrorPage_ErrorLabel", resourceCulture);
            }
        }
    }
}
