using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitle("NopCommerce")]
[assembly: AssemblyCompany("Sitecore Corporation")]
[assembly: AssemblyProduct("Sitecore Commerce Connect")]
[assembly: AssemblyCopyright("Copyright © Sitecore Corporation 1999-2014")]
[assembly: AssemblyTrademark("Sitecore® is a registered trademark of Sitecore Corporation.")]
[assembly: AssemblyVersion("7.2")]
[assembly: AssemblyInformationalVersion("7.2 rev. 140811")]
[assembly: AssemblyFileVersion("7.2.4879")]

