using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Nop.Plugin.Sitecore.Commerce.Tests")]
[assembly: AssemblyCompanyAttribute("Sitecore Corporation A/S")]
[assembly: AssemblyProductAttribute("Sitecore Commerce Connect")]
[assembly: AssemblyCopyrightAttribute("© 2016 Sitecore Corporation A/S. All rights reserved. Sitecore® is a registered trademark of Sitecore Corporation A/S.")]
[assembly: AssemblyTrademarkAttribute("Sitecore® is a registered trademark of Sitecore Corporation A/S.")]
[assembly: AssemblyVersionAttribute("0.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0-LOCAL-2016.09.22T20:21:25")]
[assembly: AssemblyFileVersionAttribute("0.0.0.0")]

