using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Nop.Plugin.Sitecore.Obec.Prices.Tests")]
[assembly: AssemblyCompanyAttribute("Sitecore Corporation")]
[assembly: AssemblyProductAttribute("Sitecore Commerce")]
[assembly: AssemblyCopyrightAttribute("Copyright © Sitecore Corporation 1999-2014")]
[assembly: AssemblyTrademarkAttribute("Sitecore® is a registered trademark of Sitecore Corporation.")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0 rev. 140513")]
[assembly: AssemblyFileVersionAttribute("1.0.4789")]

