using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Nop.Plugin.Sitecore.Obec.Prices.Tests")]
[assembly: AssemblyCompanyAttribute("Sitecore Corporation")]
[assembly: AssemblyProductAttribute("Sitecore Commerce Connect")]
[assembly: AssemblyCopyrightAttribute("© 1999 - 2016. All rights reserved. Sitecore is a registered trademark of Sitecore Corporation A/S.")]
[assembly: AssemblyTrademarkAttribute("Sitecore® is a registered trademark of Sitecore Corporation.")]
[assembly: AssemblyVersionAttribute("8.2")]
[assembly: AssemblyInformationalVersionAttribute("8.2 rev. 160216")]
[assembly: AssemblyFileVersionAttribute("8.2.5433")]

