//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Commerce.Connectors.NopCommerce.NopShippingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Common.Models")]
    [System.SerializableAttribute()]
    public partial class ShoppingCartModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel BillingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BillingAddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAnonymousField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.PaymentInfoModel PaymentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShipmentModel[] ShipmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel ShippingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShippingAddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShippingMethodModel ShippingInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShippingMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShippingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShippingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShoppingCartItemModel[] ShoppingItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StoreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel BillingAddress {
            get {
                return this.BillingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddressField, value) != true)) {
                    this.BillingAddressField = value;
                    this.RaisePropertyChanged("BillingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BillingAddressId {
            get {
                return this.BillingAddressIdField;
            }
            set {
                if ((this.BillingAddressIdField.Equals(value) != true)) {
                    this.BillingAddressIdField = value;
                    this.RaisePropertyChanged("BillingAddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingName {
            get {
                return this.BillingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingNameField, value) != true)) {
                    this.BillingNameField = value;
                    this.RaisePropertyChanged("BillingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerGuid {
            get {
                return this.CustomerGuidField;
            }
            set {
                if ((this.CustomerGuidField.Equals(value) != true)) {
                    this.CustomerGuidField = value;
                    this.RaisePropertyChanged("CustomerGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnonymous {
            get {
                return this.IsAnonymousField;
            }
            set {
                if ((this.IsAnonymousField.Equals(value) != true)) {
                    this.IsAnonymousField = value;
                    this.RaisePropertyChanged("IsAnonymous");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.PaymentInfoModel PaymentInfo {
            get {
                return this.PaymentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentInfoField, value) != true)) {
                    this.PaymentInfoField = value;
                    this.RaisePropertyChanged("PaymentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentMethodField, value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentStatus {
            get {
                return this.PaymentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentStatusField, value) != true)) {
                    this.PaymentStatusField = value;
                    this.RaisePropertyChanged("PaymentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShipmentModel[] Shipments {
            get {
                return this.ShipmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentsField, value) != true)) {
                    this.ShipmentsField = value;
                    this.RaisePropertyChanged("Shipments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel ShippingAddress {
            get {
                return this.ShippingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingAddressField, value) != true)) {
                    this.ShippingAddressField = value;
                    this.RaisePropertyChanged("ShippingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShippingAddressId {
            get {
                return this.ShippingAddressIdField;
            }
            set {
                if ((this.ShippingAddressIdField.Equals(value) != true)) {
                    this.ShippingAddressIdField = value;
                    this.RaisePropertyChanged("ShippingAddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShippingMethodModel ShippingInfo {
            get {
                return this.ShippingInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingInfoField, value) != true)) {
                    this.ShippingInfoField = value;
                    this.RaisePropertyChanged("ShippingInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingMethod {
            get {
                return this.ShippingMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingMethodField, value) != true)) {
                    this.ShippingMethodField = value;
                    this.RaisePropertyChanged("ShippingMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingName {
            get {
                return this.ShippingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingNameField, value) != true)) {
                    this.ShippingNameField = value;
                    this.RaisePropertyChanged("ShippingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingStatus {
            get {
                return this.ShippingStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingStatusField, value) != true)) {
                    this.ShippingStatusField = value;
                    this.RaisePropertyChanged("ShippingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShoppingCartItemModel[] ShoppingItems {
            get {
                return this.ShoppingItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingItemsField, value) != true)) {
                    this.ShoppingItemsField = value;
                    this.RaisePropertyChanged("ShoppingItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StoreId {
            get {
                return this.StoreIdField;
            }
            set {
                if ((this.StoreIdField.Equals(value) != true)) {
                    this.StoreIdField = value;
                    this.RaisePropertyChanged("StoreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Common.Models")]
    [System.SerializableAttribute()]
    public partial class AddressModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryThreeLetterIsoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryTwoLetterIsoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateProvinceAbbreviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipPostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryThreeLetterIsoCode {
            get {
                return this.CountryThreeLetterIsoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryThreeLetterIsoCodeField, value) != true)) {
                    this.CountryThreeLetterIsoCodeField = value;
                    this.RaisePropertyChanged("CountryThreeLetterIsoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryTwoLetterIsoCode {
            get {
                return this.CountryTwoLetterIsoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryTwoLetterIsoCodeField, value) != true)) {
                    this.CountryTwoLetterIsoCodeField = value;
                    this.RaisePropertyChanged("CountryTwoLetterIsoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNumber {
            get {
                return this.FaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumberField, value) != true)) {
                    this.FaxNumberField = value;
                    this.RaisePropertyChanged("FaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvinceAbbreviation {
            get {
                return this.StateProvinceAbbreviationField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceAbbreviationField, value) != true)) {
                    this.StateProvinceAbbreviationField = value;
                    this.RaisePropertyChanged("StateProvinceAbbreviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipPostalCode {
            get {
                return this.ZipPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipPostalCodeField, value) != true)) {
                    this.ZipPostalCodeField = value;
                    this.RaisePropertyChanged("ZipPostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentInfoModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Common.Models")]
    [System.SerializableAttribute()]
    public partial class PaymentInfoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemName {
            get {
                return this.SystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemNameField, value) != true)) {
                    this.SystemNameField = value;
                    this.RaisePropertyChanged("SystemName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShippingMethodModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Common.Models")]
    [System.SerializableAttribute()]
    public partial class ShippingMethodModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemName {
            get {
                return this.SystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemNameField, value) != true)) {
                    this.SystemNameField = value;
                    this.RaisePropertyChanged("SystemName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Common.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShoppingCartModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.PaymentInfoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShipmentModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShippingMethodModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShoppingCartItemModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShoppingCartItemModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ArrayOfShippingMethodModelResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShippingMethodModel[]))]
    public partial class ShipmentModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ItemsIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShippingAddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShippingMethodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] ItemsIDs {
            get {
                return this.ItemsIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsIDsField, value) != true)) {
                    this.ItemsIDsField = value;
                    this.RaisePropertyChanged("ItemsIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShippingAddressId {
            get {
                return this.ShippingAddressIdField;
            }
            set {
                if ((this.ShippingAddressIdField.Equals(value) != true)) {
                    this.ShippingAddressIdField = value;
                    this.RaisePropertyChanged("ShippingAddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingMethod {
            get {
                return this.ShippingMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingMethodField, value) != true)) {
                    this.ShippingMethodField = value;
                    this.RaisePropertyChanged("ShippingMethod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartItemModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Common.Models")]
    [System.SerializableAttribute()]
    public partial class ShoppingCartItemModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LineTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineTotal {
            get {
                return this.LineTotalField;
            }
            set {
                if ((this.LineTotalField.Equals(value) != true)) {
                    this.LineTotalField = value;
                    this.RaisePropertyChanged("LineTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sku {
            get {
                return this.SkuField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuField, value) != true)) {
                    this.SkuField = value;
                    this.RaisePropertyChanged("Sku");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrayOfShippingMethodModelResponse", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Common.Models")]
    [System.SerializableAttribute()]
    public partial class ArrayOfShippingMethodModelResponse : Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShippingMethodModel[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShippingMethodModel[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Common.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ArrayOfShippingMethodModelResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NopShippingService.IShippingService")]
    public interface IShippingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShippingService/GetShippingMethods", ReplyAction="http://tempuri.org/IShippingService/GetShippingMethodsResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ArrayOfShippingMethodModelResponse GetShippingMethods(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShoppingCartModel shoppingCartModel, string storeName, Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel addressModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShippingService/GetShippingMethods", ReplyAction="http://tempuri.org/IShippingService/GetShippingMethodsResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ArrayOfShippingMethodModelResponse> GetShippingMethodsAsync(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShoppingCartModel shoppingCartModel, string storeName, Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel addressModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShippingServiceChannel : Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.IShippingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShippingServiceClient : System.ServiceModel.ClientBase<Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.IShippingService>, Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.IShippingService {
        
        public ShippingServiceClient() {
        }
        
        public ShippingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShippingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ArrayOfShippingMethodModelResponse GetShippingMethods(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShoppingCartModel shoppingCartModel, string storeName, Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel addressModel) {
            return base.Channel.GetShippingMethods(shoppingCartModel, storeName, addressModel);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ArrayOfShippingMethodModelResponse> GetShippingMethodsAsync(Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.ShoppingCartModel shoppingCartModel, string storeName, Sitecore.Commerce.Connectors.NopCommerce.NopShippingService.AddressModel addressModel) {
            return base.Channel.GetShippingMethodsAsync(shoppingCartModel, storeName, addressModel);
        }
    }
}
