//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Commerce.Connectors.NopCommerce.NopProductsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class ProductModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CategoryIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GtinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ManufacturerIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerPartNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaKeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductGlobalSpecificationModel[] ProductGlobalSpecificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductVariantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductVariantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowOnHomePageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminComment {
            get {
                return this.AdminCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminCommentField, value) != true)) {
                    this.AdminCommentField = value;
                    this.RaisePropertyChanged("AdminComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CategoryIds {
            get {
                return this.CategoryIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdsField, value) != true)) {
                    this.CategoryIdsField = value;
                    this.RaisePropertyChanged("CategoryIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullDescription {
            get {
                return this.FullDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FullDescriptionField, value) != true)) {
                    this.FullDescriptionField = value;
                    this.RaisePropertyChanged("FullDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gtin {
            get {
                return this.GtinField;
            }
            set {
                if ((object.ReferenceEquals(this.GtinField, value) != true)) {
                    this.GtinField = value;
                    this.RaisePropertyChanged("Gtin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ManufacturerIds {
            get {
                return this.ManufacturerIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerIdsField, value) != true)) {
                    this.ManufacturerIdsField = value;
                    this.RaisePropertyChanged("ManufacturerIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufacturerPartNumber {
            get {
                return this.ManufacturerPartNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerPartNumberField, value) != true)) {
                    this.ManufacturerPartNumberField = value;
                    this.RaisePropertyChanged("ManufacturerPartNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDescription {
            get {
                return this.MetaDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDescriptionField, value) != true)) {
                    this.MetaDescriptionField = value;
                    this.RaisePropertyChanged("MetaDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaKeywords {
            get {
                return this.MetaKeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaKeywordsField, value) != true)) {
                    this.MetaKeywordsField = value;
                    this.RaisePropertyChanged("MetaKeywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaTitle {
            get {
                return this.MetaTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaTitleField, value) != true)) {
                    this.MetaTitleField = value;
                    this.RaisePropertyChanged("MetaTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductGlobalSpecificationModel[] ProductGlobalSpecifications {
            get {
                return this.ProductGlobalSpecificationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductGlobalSpecificationsField, value) != true)) {
                    this.ProductGlobalSpecificationsField = value;
                    this.RaisePropertyChanged("ProductGlobalSpecifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductVariantId {
            get {
                return this.ProductVariantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductVariantIdField, value) != true)) {
                    this.ProductVariantIdField = value;
                    this.RaisePropertyChanged("ProductVariantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductVariantName {
            get {
                return this.ProductVariantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductVariantNameField, value) != true)) {
                    this.ProductVariantNameField = value;
                    this.RaisePropertyChanged("ProductVariantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published {
            get {
                return this.PublishedField;
            }
            set {
                if ((this.PublishedField.Equals(value) != true)) {
                    this.PublishedField = value;
                    this.RaisePropertyChanged("Published");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeName {
            get {
                return this.SeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SeNameField, value) != true)) {
                    this.SeNameField = value;
                    this.RaisePropertyChanged("SeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowOnHomePage {
            get {
                return this.ShowOnHomePageField;
            }
            set {
                if ((this.ShowOnHomePageField.Equals(value) != true)) {
                    this.ShowOnHomePageField = value;
                    this.RaisePropertyChanged("ShowOnHomePage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sku {
            get {
                return this.SkuField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuField, value) != true)) {
                    this.SkuField = value;
                    this.RaisePropertyChanged("Sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductGlobalSpecificationModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class ProductGlobalSpecificationModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LookupValueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LookupValueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecificationLookupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecificationLookupNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomValue {
            get {
                return this.CustomValueField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomValueField, value) != true)) {
                    this.CustomValueField = value;
                    this.RaisePropertyChanged("CustomValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LookupValueId {
            get {
                return this.LookupValueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LookupValueIdField, value) != true)) {
                    this.LookupValueIdField = value;
                    this.RaisePropertyChanged("LookupValueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LookupValueName {
            get {
                return this.LookupValueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LookupValueNameField, value) != true)) {
                    this.LookupValueNameField = value;
                    this.RaisePropertyChanged("LookupValueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecificationLookupId {
            get {
                return this.SpecificationLookupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecificationLookupIdField, value) != true)) {
                    this.SpecificationLookupIdField = value;
                    this.RaisePropertyChanged("SpecificationLookupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecificationLookupName {
            get {
                return this.SpecificationLookupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecificationLookupNameField, value) != true)) {
                    this.SpecificationLookupNameField = value;
                    this.RaisePropertyChanged("SpecificationLookupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManufacturerModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class ManufacturerModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published {
            get {
                return this.PublishedField;
            }
            set {
                if ((this.PublishedField.Equals(value) != true)) {
                    this.PublishedField = value;
                    this.RaisePropertyChanged("Published");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class CategoryModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaKeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDescription {
            get {
                return this.MetaDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDescriptionField, value) != true)) {
                    this.MetaDescriptionField = value;
                    this.RaisePropertyChanged("MetaDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaKeywords {
            get {
                return this.MetaKeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaKeywordsField, value) != true)) {
                    this.MetaKeywordsField = value;
                    this.RaisePropertyChanged("MetaKeywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaTitle {
            get {
                return this.MetaTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaTitleField, value) != true)) {
                    this.MetaTitleField = value;
                    this.RaisePropertyChanged("MetaTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentCategoryId {
            get {
                return this.ParentCategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentCategoryIdField, value) != true)) {
                    this.ParentCategoryIdField = value;
                    this.RaisePropertyChanged("ParentCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published {
            get {
                return this.PublishedField;
            }
            set {
                if ((this.PublishedField.Equals(value) != true)) {
                    this.PublishedField = value;
                    this.RaisePropertyChanged("Published");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecificationLookupModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class SpecificationLookupModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.LookupValueModel[] SpecificationOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.LookupValueModel[] SpecificationOptions {
            get {
                return this.SpecificationOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecificationOptionsField, value) != true)) {
                    this.SpecificationOptionsField = value;
                    this.RaisePropertyChanged("SpecificationOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupValueModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class LookupValueModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIdField, value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DivisionModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class DivisionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDivisionsModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class ProductDivisionsModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.DivisionModel[] DivisionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.DivisionModel[] Divisions {
            get {
                return this.DivisionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionsField, value) != true)) {
                    this.DivisionsField = value;
                    this.RaisePropertyChanged("Divisions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductManufacturersModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class ProductManufacturersModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[] ManufacturersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[] Manufacturers {
            get {
                return this.ManufacturersField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturersField, value) != true)) {
                    this.ManufacturersField = value;
                    this.RaisePropertyChanged("Manufacturers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductTypeModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class ProductTypeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaKeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentProductTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDescription {
            get {
                return this.MetaDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDescriptionField, value) != true)) {
                    this.MetaDescriptionField = value;
                    this.RaisePropertyChanged("MetaDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaKeywords {
            get {
                return this.MetaKeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaKeywordsField, value) != true)) {
                    this.MetaKeywordsField = value;
                    this.RaisePropertyChanged("MetaKeywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaTitle {
            get {
                return this.MetaTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaTitleField, value) != true)) {
                    this.MetaTitleField = value;
                    this.RaisePropertyChanged("MetaTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentProductTypeId {
            get {
                return this.ParentProductTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentProductTypeIdField, value) != true)) {
                    this.ParentProductTypeIdField = value;
                    this.RaisePropertyChanged("ParentProductTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published {
            get {
                return this.PublishedField;
            }
            set {
                if ((this.PublishedField.Equals(value) != true)) {
                    this.PublishedField = value;
                    this.RaisePropertyChanged("Published");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductResourceModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class ProductResourceModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductResourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ResourceModel[] ResourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductResourceType {
            get {
                return this.ProductResourceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductResourceTypeField, value) != true)) {
                    this.ProductResourceTypeField = value;
                    this.RaisePropertyChanged("ProductResourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ResourceModel[] Resources {
            get {
                return this.ResourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourcesField, value) != true)) {
                    this.ResourcesField = value;
                    this.RaisePropertyChanged("Resources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceModel", Namespace="http://schemas.datacontract.org/2004/07/Sitecore.Commerce.Nop.Products.Models")]
    [System.SerializableAttribute()]
    public partial class ResourceModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BinaryDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BinaryData {
            get {
                return this.BinaryDataField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaryDataField, value) != true)) {
                    this.BinaryDataField = value;
                    this.RaisePropertyChanged("BinaryData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType {
            get {
                return this.MimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MimeTypeField, value) != true)) {
                    this.MimeTypeField = value;
                    this.RaisePropertyChanged("MimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceType {
            get {
                return this.ResourceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceTypeField, value) != true)) {
                    this.ResourceTypeField = value;
                    this.RaisePropertyChanged("ResourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NopProductsService.IProductsService")]
    public interface IProductsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProduct", ReplyAction="http://tempuri.org/IProductsService/GetProductResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductModel GetProduct(string externalProductId, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProduct", ReplyAction="http://tempuri.org/IProductsService/GetProductResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductModel> GetProductAsync(string externalProductId, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllProductsIds", ReplyAction="http://tempuri.org/IProductsService/GetAllProductsIdsResponse")]
        string[] GetAllProductsIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllProductsIds", ReplyAction="http://tempuri.org/IProductsService/GetAllProductsIdsResponse")]
        System.Threading.Tasks.Task<string[]> GetAllProductsIdsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetManufacturer", ReplyAction="http://tempuri.org/IProductsService/GetManufacturerResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[] GetManufacturer(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetManufacturer", ReplyAction="http://tempuri.org/IProductsService/GetManufacturerResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[]> GetManufacturerAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllManufacturers", ReplyAction="http://tempuri.org/IProductsService/GetAllManufacturersResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[] GetAllManufacturers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllManufacturers", ReplyAction="http://tempuri.org/IProductsService/GetAllManufacturersResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[]> GetAllManufacturersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetCategories", ReplyAction="http://tempuri.org/IProductsService/GetCategoriesResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.CategoryModel[] GetCategories(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetCategories", ReplyAction="http://tempuri.org/IProductsService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.CategoryModel[]> GetCategoriesAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllCategories", ReplyAction="http://tempuri.org/IProductsService/GetAllCategoriesResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.CategoryModel[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllCategories", ReplyAction="http://tempuri.org/IProductsService/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.CategoryModel[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllGlobalSpecifications", ReplyAction="http://tempuri.org/IProductsService/GetAllGlobalSpecificationsResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.SpecificationLookupModel[] GetAllGlobalSpecifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllGlobalSpecifications", ReplyAction="http://tempuri.org/IProductsService/GetAllGlobalSpecificationsResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.SpecificationLookupModel[]> GetAllGlobalSpecificationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductGlobalSpecifications", ReplyAction="http://tempuri.org/IProductsService/GetProductGlobalSpecificationsResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductGlobalSpecificationModel[] GetProductGlobalSpecifications(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductGlobalSpecifications", ReplyAction="http://tempuri.org/IProductsService/GetProductGlobalSpecificationsResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductGlobalSpecificationModel[]> GetProductGlobalSpecificationsAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetRelatedProductsIds", ReplyAction="http://tempuri.org/IProductsService/GetRelatedProductsIdsResponse")]
        string[] GetRelatedProductsIds(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetRelatedProductsIds", ReplyAction="http://tempuri.org/IProductsService/GetRelatedProductsIdsResponse")]
        System.Threading.Tasks.Task<string[]> GetRelatedProductsIdsAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetCrossSellProductsIds", ReplyAction="http://tempuri.org/IProductsService/GetCrossSellProductsIdsResponse")]
        string[] GetCrossSellProductsIds(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetCrossSellProductsIds", ReplyAction="http://tempuri.org/IProductsService/GetCrossSellProductsIdsResponse")]
        System.Threading.Tasks.Task<string[]> GetCrossSellProductsIdsAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetVariantProductsIds", ReplyAction="http://tempuri.org/IProductsService/GetVariantProductsIdsResponse")]
        string[] GetVariantProductsIds(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetVariantProductsIds", ReplyAction="http://tempuri.org/IProductsService/GetVariantProductsIdsResponse")]
        System.Threading.Tasks.Task<string[]> GetVariantProductsIdsAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllDivisions", ReplyAction="http://tempuri.org/IProductsService/GetAllDivisionsResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.DivisionModel[] GetAllDivisions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllDivisions", ReplyAction="http://tempuri.org/IProductsService/GetAllDivisionsResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.DivisionModel[]> GetAllDivisionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetRelatedDivisions", ReplyAction="http://tempuri.org/IProductsService/GetRelatedDivisionsResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductDivisionsModel GetRelatedDivisions(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetRelatedDivisions", ReplyAction="http://tempuri.org/IProductsService/GetRelatedDivisionsResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductDivisionsModel> GetRelatedDivisionsAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductManufacturers", ReplyAction="http://tempuri.org/IProductsService/GetProductManufacturersResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductManufacturersModel GetProductManufacturers(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductManufacturers", ReplyAction="http://tempuri.org/IProductsService/GetProductManufacturersResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductManufacturersModel> GetProductManufacturersAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllProductTypes", ReplyAction="http://tempuri.org/IProductsService/GetAllProductTypesResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductTypeModel[] GetAllProductTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllProductTypes", ReplyAction="http://tempuri.org/IProductsService/GetAllProductTypesResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductTypeModel[]> GetAllProductTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductTypes", ReplyAction="http://tempuri.org/IProductsService/GetProductTypesResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductTypeModel[] GetProductTypes(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductTypes", ReplyAction="http://tempuri.org/IProductsService/GetProductTypesResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductTypeModel[]> GetProductTypesAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductMainImage", ReplyAction="http://tempuri.org/IProductsService/GetProductMainImageResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel GetProductMainImage(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductMainImage", ReplyAction="http://tempuri.org/IProductsService/GetProductMainImageResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel> GetProductMainImageAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductAlternateImages", ReplyAction="http://tempuri.org/IProductsService/GetProductAlternateImagesResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel GetProductAlternateImages(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductAlternateImages", ReplyAction="http://tempuri.org/IProductsService/GetProductAlternateImagesResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel> GetProductAlternateImagesAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductDownloads", ReplyAction="http://tempuri.org/IProductsService/GetProductDownloadsResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel GetProductDownloads(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductDownloads", ReplyAction="http://tempuri.org/IProductsService/GetProductDownloadsResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel> GetProductDownloadsAsync(string externalProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllResources", ReplyAction="http://tempuri.org/IProductsService/GetAllResourcesResponse")]
        Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ResourceModel[] GetAllResources();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetAllResources", ReplyAction="http://tempuri.org/IProductsService/GetAllResourcesResponse")]
        System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ResourceModel[]> GetAllResourcesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/UpdateProduct", ReplyAction="http://tempuri.org/IProductsService/UpdateProductResponse")]
        void UpdateProduct(Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductModel product, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/UpdateProduct", ReplyAction="http://tempuri.org/IProductsService/UpdateProductResponse")]
        System.Threading.Tasks.Task UpdateProductAsync(Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductModel product, string languageCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductsServiceChannel : Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.IProductsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsServiceClient : System.ServiceModel.ClientBase<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.IProductsService>, Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.IProductsService {
        
        public ProductsServiceClient() {
        }
        
        public ProductsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductModel GetProduct(string externalProductId, string languageCode) {
            return base.Channel.GetProduct(externalProductId, languageCode);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductModel> GetProductAsync(string externalProductId, string languageCode) {
            return base.Channel.GetProductAsync(externalProductId, languageCode);
        }
        
        public string[] GetAllProductsIds() {
            return base.Channel.GetAllProductsIds();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllProductsIdsAsync() {
            return base.Channel.GetAllProductsIdsAsync();
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[] GetManufacturer(string externalProductId) {
            return base.Channel.GetManufacturer(externalProductId);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[]> GetManufacturerAsync(string externalProductId) {
            return base.Channel.GetManufacturerAsync(externalProductId);
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[] GetAllManufacturers() {
            return base.Channel.GetAllManufacturers();
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ManufacturerModel[]> GetAllManufacturersAsync() {
            return base.Channel.GetAllManufacturersAsync();
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.CategoryModel[] GetCategories(string externalProductId) {
            return base.Channel.GetCategories(externalProductId);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.CategoryModel[]> GetCategoriesAsync(string externalProductId) {
            return base.Channel.GetCategoriesAsync(externalProductId);
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.CategoryModel[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.CategoryModel[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.SpecificationLookupModel[] GetAllGlobalSpecifications() {
            return base.Channel.GetAllGlobalSpecifications();
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.SpecificationLookupModel[]> GetAllGlobalSpecificationsAsync() {
            return base.Channel.GetAllGlobalSpecificationsAsync();
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductGlobalSpecificationModel[] GetProductGlobalSpecifications(string externalProductId) {
            return base.Channel.GetProductGlobalSpecifications(externalProductId);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductGlobalSpecificationModel[]> GetProductGlobalSpecificationsAsync(string externalProductId) {
            return base.Channel.GetProductGlobalSpecificationsAsync(externalProductId);
        }
        
        public string[] GetRelatedProductsIds(string externalProductId) {
            return base.Channel.GetRelatedProductsIds(externalProductId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRelatedProductsIdsAsync(string externalProductId) {
            return base.Channel.GetRelatedProductsIdsAsync(externalProductId);
        }
        
        public string[] GetCrossSellProductsIds(string externalProductId) {
            return base.Channel.GetCrossSellProductsIds(externalProductId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCrossSellProductsIdsAsync(string externalProductId) {
            return base.Channel.GetCrossSellProductsIdsAsync(externalProductId);
        }
        
        public string[] GetVariantProductsIds(string externalProductId) {
            return base.Channel.GetVariantProductsIds(externalProductId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetVariantProductsIdsAsync(string externalProductId) {
            return base.Channel.GetVariantProductsIdsAsync(externalProductId);
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.DivisionModel[] GetAllDivisions() {
            return base.Channel.GetAllDivisions();
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.DivisionModel[]> GetAllDivisionsAsync() {
            return base.Channel.GetAllDivisionsAsync();
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductDivisionsModel GetRelatedDivisions(string externalProductId) {
            return base.Channel.GetRelatedDivisions(externalProductId);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductDivisionsModel> GetRelatedDivisionsAsync(string externalProductId) {
            return base.Channel.GetRelatedDivisionsAsync(externalProductId);
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductManufacturersModel GetProductManufacturers(string externalProductId) {
            return base.Channel.GetProductManufacturers(externalProductId);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductManufacturersModel> GetProductManufacturersAsync(string externalProductId) {
            return base.Channel.GetProductManufacturersAsync(externalProductId);
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductTypeModel[] GetAllProductTypes() {
            return base.Channel.GetAllProductTypes();
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductTypeModel[]> GetAllProductTypesAsync() {
            return base.Channel.GetAllProductTypesAsync();
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductTypeModel[] GetProductTypes(string externalProductId) {
            return base.Channel.GetProductTypes(externalProductId);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductTypeModel[]> GetProductTypesAsync(string externalProductId) {
            return base.Channel.GetProductTypesAsync(externalProductId);
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel GetProductMainImage(string externalProductId) {
            return base.Channel.GetProductMainImage(externalProductId);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel> GetProductMainImageAsync(string externalProductId) {
            return base.Channel.GetProductMainImageAsync(externalProductId);
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel GetProductAlternateImages(string externalProductId) {
            return base.Channel.GetProductAlternateImages(externalProductId);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel> GetProductAlternateImagesAsync(string externalProductId) {
            return base.Channel.GetProductAlternateImagesAsync(externalProductId);
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel GetProductDownloads(string externalProductId) {
            return base.Channel.GetProductDownloads(externalProductId);
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductResourceModel> GetProductDownloadsAsync(string externalProductId) {
            return base.Channel.GetProductDownloadsAsync(externalProductId);
        }
        
        public Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ResourceModel[] GetAllResources() {
            return base.Channel.GetAllResources();
        }
        
        public System.Threading.Tasks.Task<Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ResourceModel[]> GetAllResourcesAsync() {
            return base.Channel.GetAllResourcesAsync();
        }
        
        public void UpdateProduct(Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductModel product, string languageCode) {
            base.Channel.UpdateProduct(product, languageCode);
        }
        
        public System.Threading.Tasks.Task UpdateProductAsync(Sitecore.Commerce.Connectors.NopCommerce.NopProductsService.ProductModel product, string languageCode) {
            return base.Channel.UpdateProductAsync(product, languageCode);
        }
    }
}
