using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("NopCommerce.Tests")]
[assembly: AssemblyCompanyAttribute("Sitecore Corporation")]
[assembly: AssemblyProductAttribute("Sitecore Commerce Connect")]
[assembly: AssemblyCopyrightAttribute("Copyright © Sitecore Corporation 1999-2014")]
[assembly: AssemblyTrademarkAttribute("Sitecore® is a registered trademark of Sitecore Corporation.")]
[assembly: AssemblyVersionAttribute("7.2")]
[assembly: AssemblyInformationalVersionAttribute("7.2 rev. 140811")]
[assembly: AssemblyFileVersionAttribute("7.2.4879")]

